### ISSUE TITLE
meta data export

### ISSUE THREAD

**Issue by MartinKl** [korpling/pepperModules-EXMARaLDAModules#1]
It seems, that meta data are not exported to EXMARaLDA format. Check whether the cause is the EXMARaLDAExporter or the EXMARaLDAModel (EXBWriter).

**Comment by amir-zeldes** [comment]
I just ran into this too. Should the exporter support these as <ud-meta-information> or try to use built in metadata? I would prefer to handle everything as ud-meta-information, since we can't predict what metadata fields users pick and this is a more generic solution. (I believe ud stands for user-defined(?))

**Comment by thomaskrause** [comment]
Should be fixed by  fe8072c24a572d3f276500335458f80025776e85
